### ISSUE TITLE
if you look at my page you can find a page for vs Dave and Bambi Mac fix source

### ISSUE THREAD

**Issue by Gothbr4dn** [FuseIsHere813/VsDave#10]
just wanted to let you know you can build the game for Mac and it work

also I made the shaders file show up but if you want to build it delete it

https://github.com/BushsHaxs/Vs-Dave-fixed

**Comment by ghost** [comment]
You should start a pull request for that

**Comment by ghost** [comment]
oh wait u did. nvm.
