### ISSUE TITLE
Bug Report: I can't build the game on mac because of source/Note.hx:11: characters 8-33 : Type not found : polymod.format.ParseRules

### ISSUE THREAD

**Issue by the-funky-lad** [FuseIsHere813/VsDave#14]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by br4dnblehh** [comment]
i fixed the source code if you want it

**Comment by br4dnblehh** [comment]
here is the link
https://github.com/BushsHaxs/Vs-Dave-fixed

**Comment by ghost** [comment]
you have to install polymod to make it work

**Comment by the-funky-lad** [comment]
nvm i had the latest version of haxe for psych engine. now i have 4.1.5
