### ISSUE TITLE
I need some help.

### ISSUE THREAD

**Issue by Joalor64** [FuseIsHere813/VsDave#22]
What line in FreeplayState.hx and PauseSubState.hx makes the menus move in a disc-like way? I want to copy the code into my own engine.

**Comment by FuseIsHere813** [comment]
I am not sure but I'll check the disc like code.

**Comment by Joalor64** [comment]
ok

**Comment by FuseIsHere813** [comment]
I can't find it in PauseSubState and FreeplayState, try check PlayState.hx?
