### ISSUE TITLE
Maze FLP Saved on Trial

### ISSUE THREAD

**Issue by juanroman74454811** [FuseIsHere813/VsDave#3]
Why did you save it in trial? I just wanted to make a cover

**Comment by FuseIsHere813** [comment]
Try checking out this fork: https://github.com/retest672/VsDave

**Comment by FuseIsHere813** [comment]
Acutally, the file is not on trial, you saved it in trial mode.

**Comment by juanroman74454811** [comment]
> Acutally, the file is not on trial, you saved it in trial mode.

![GhostTwinsMergedIcon](https://user-images.githubusercontent.com/92176733/147960991-37d55c76-5465-4e66-90a5-1bd029a4c387.png)
![haha yes](https://user-images.githubusercontent.com/92176733/147960995-20f6fd57-73a1-4760-b27c-907359248025.png)
![i am epic](https://user-images.githubusercontent.com/92176733/147960996-a1bf9b62-7a11-4bb7-acb9-a967f51e6f6a.png)
![i hate steam](https://user-images.githubusercontent.com/92176733/147960999-9afd442d-d224-42eb-affe-1259e528faa6.png)
![584830fecef1014c0b5e4aa2](https://user-images.githubusercontent.com/92176733/147961011-6d0f8951-b3e3-4ee6-9487-29ded9b9558c.png)
Heres some free images and a yummy raspberry!!! Hope you enjoy!
