### ISSUE TITLE
Where exactly is cheating/unfairnesses modchart?

### ISSUE THREAD

**Issue by PikrlRealForReal** [FuseIsHere813/VsDave#32]
Ik they are in playstate.hx , but where?

**Comment by ghost** [comment]
Cheating (strum movement):
https://github.com/FuseIsHere813/VsDave/blob/afbed891070e98512a60bd9645fcb6fdaa821f1a/source/PlayState.hx#L1612-L1624

Unfairness (strum movement):
https://github.com/FuseIsHere813/VsDave/blob/afbed891070e98512a60bd9645fcb6fdaa821f1a/source/PlayState.hx#L1626-L1638

Unfairness (scroll speed changes):
https://github.com/FuseIsHere813/VsDave/blob/afbed891070e98512a60bd9645fcb6fdaa821f1a/source/PlayState.hx#L2111-L2115

I couldn't find the script for Cheating that fucks up the notes.

**Comment by raf13lol** [comment]
it uses mystrum to mess with them

**Comment by ghost** [comment]
> it uses mystrum to mess with them

I mean like flipping the notes and making you press down on a right arrow.

**Comment by raf13lol** [comment]
oh
