### ISSUE TITLE
Enhancement: Adding 3.0

### ISSUE THREAD

**Issue by MrMichaDaDude** [FuseIsHere813/VsDave#41]
Please Add

**Comment by mayo78** [comment]
the source for 3.0 isnt even out yet and also this repo isnt owned by any of the devs

**Comment by charlesisfeline** [comment]
the full 3.0 update isnt out yet, and not all secrets have been found by the devs currently
the 3.0 source code will be out once both of these are solved

**Comment by charlesisfeline** [comment]
> the source for 3.0 isnt even out yet and also this repo isnt owned by any of the devs

yea its a fork, before the official repo got privated

**Comment by FuseIsHere813** [comment]
No 3.0 repository exists, wait for the devs to release it.

**Comment by mayo78** [comment]
https://github.com/MoldyGH/VsDave
